import type { ILandlordRef, IPropertyRef } from "@/store/types/common";
import type { ICategory } from "./dbCategory";

// LISTINGS

export type TListingStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "active"
  | "inactive";

export interface IListingUnit {
  id: string;
  code: string;
  area_sq_m: number;
  bedrooms: number;
  bathrooms: number;
  status: string;
  property: IPropertyRef;
}

export interface IListing {
  id: string;
  title: string;
  description: string;
  listedPrice: number;
  isPublic: boolean;
  status: TListingStatus;
  createdAt: string;
  unitId: IListingUnit;
  landlordId: ILandlordRef;
  featured?: boolean;
  category?: ICategory;
  image?: string;
}

export const dbListings: IListing[] = [
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l1",
    title: "Căn hộ 2PN view đẹp Quận 7",
    description:
      "Căn hộ cao cấp 2 phòng ngủ, 2 wc, ban công rộng, view sông Sài Gòn. Đầy đủ nội thất.",
    listed_price: 8500000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-15T09:00:00Z",
    unit: {
      id: "u1",
      code: "A-101",
      area_sq_m: 65,
      bedrooms: 2,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l2",
    title: "Căn hộ 3PN giá tốt Golden Star",
    description: "Căn hộ 3 phòng ngủ rộng rãi, thoáng mát, an ninh 24/7.",
    listed_price: 10000000,
    is_public: true,
    status: "approved",
    created_at: "2024-10-20T11:00:00Z",
    unit: {
      id: "u3",
      code: "B-201",
      area_sq_m: 75,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Chung cư Golden Star",
        address: "123 Nguyễn Văn Linh, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: false,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l3",
    title: "Căn hộ cao cấp 3PN Sunrise City",
    description:
      "Căn hộ cao cấp 85m2, đầy đủ tiện nghi hiện đại. Gần Lotte Mart, PMH.",
    listed_price: 12000000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-01T10:00:00Z",
    unit: {
      id: "u4",
      code: "C-301",
      area_sq_m: 85,
      bedrooms: 3,
      bathrooms: 2,
      status: "available",
      property: {
        name: "Căn hộ Sunrise City",
        address: "456 Nguyễn Hữu Thọ, Q7, TPHCM",
        district: "Quận 7",
      },
    },
    landlord: {
      id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      display_name: "Nguyễn Văn Hùng",
      verified: true,
      rating: 4.8,
    },
    featured: true,
    category: { label: "Căn Hộ", slug: "/can-ho", value: "can-ho" },
    image: "images/room/room-rental-modern.jpg",
  },
  {
    id: "l4",
    title: "Phòng trọ giá rẻ Quận 9",
    description:
      "Phòng trọ sạch sẽ, đầy đủ tiện nghi cơ bản. Gần trường ĐH, KCX.",
    listed_price: 3500000,
    is_public: true,
    status: "approved",
    created_at: "2024-11-05T13:30:00Z",
    unit: {
      id: "u6",
      code: "P-02",
      area_sq_m: 25,
      bedrooms: 1,
      bathrooms: 1,
      status: "available",
      property: {
        name: "Nhà trọ An Phú",
        address: "789 Lê Văn Việt, Q9, TPHCM",
        district: "Quận 9",
      },
    },
    landlord: {
      id: "d4e5f6a7-b8c9-0123-def1-234567890123",
      display_name: "Lê Thị Mai",
      verified: true,
      rating: 4.6,
    },
    featured: false,
    category: { label: "Phòng Trọ", slug: "/phong-tro", value: "phong-tro" },
    image: "images/room/room-rental-modern.jpg",
  },
];
